In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
training_df= pd.read_csv("/content/drive/MyDrive/train.csv")
training_df.head(10)

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
0,0,0.603610,-7.636942,0.023500,0.000005,0.000001,0.051385,0.409866,290715.6450,0.826267,147.53020
1,1,0.639451,-16.267598,0.071520,0.444929,0.349414,0.170522,0.651010,164519.5174,0.145400,136.15963
2,2,0.514538,-15.953575,0.110715,0.173699,0.453814,0.029576,0.423865,174495.5667,0.624667,55.31989
3,3,0.734463,-1.357000,0.052965,0.001651,0.159717,0.086366,0.278745,225567.4651,0.487467,147.91212
4,4,0.532968,-13.056437,0.023500,0.068687,0.000001,0.331345,0.477769,213960.6789,0.947333,89.58511
5,5,0.594579,-11.715431,0.101701,0.000005,0.259634,0.024300,0.639254,161012.2221,0.938333,151.43602
6,6,0.714958,-8.809725,0.023500,0.471139,0.000001,0.356775,0.724783,243432.5794,0.336800,151.63439
7,7,0.703726,-10.482610,0.037751,0.115727,0.000001,0.024300,0.773899,293848.8919,0.722000,123.31545
8,8,0.455598,-1.357000,0.162537,0.173626,0.000001,0.288465,0.651137,271215.8237,0.947267,133.59806
9,9,0.431498,-5.935425,0.023500,0.439565,0.184462,0.114921,0.025600,222030.4794,0.950867,117.39790

In [ ]:
training_df.describe()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
count,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000
mean,262081.500000,0.632843,-8.379014,0.074443,0.262913,0.117690,0.178398,0.555843,241903.692949,0.500923,119.034899
std,151313.257586,0.156899,4.616221,0.049939,0.223120,0.131845,0.118186,0.225480,59326.601501,0.289952,26.468077
min,0.000000,0.076900,-27.509725,0.023500,0.000005,0.000001,0.024300,0.025600,63973.000000,0.000067,46.718000
25%,131040.750000,0.515850,-11.551933,0.023500,0.069413,0.000001,0.077637,0.403921,207099.876625,0.254933,101.070410
50%,262081.500000,0.634686,-8.252499,0.066425,0.242502,0.074247,0.166327,0.564817,243684.058150,0.511800,118.747660
75%,393122.250000,0.739179,-4.912298,0.107343,0.396957,0.204065,0.268946,0.716633,281851.658500,0.746000,136.686590
max,524163.000000,0.975000,-1.357000,0.256401,0.995000,0.869258,0.599924,0.978000,464723.228100,1.000000,206.037000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

training_df["TrackDurationMs"]= scaler.fit_transform(training_df[["TrackDurationMs"]])
training_df["AudioLoudness"]= scaler.fit_transform(training_df[["AudioLoudness"]])

In [ ]:
training_df.describe()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy,BeatsPerMinute
count,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000,524164.000000
mean,262081.500000,0.632843,0.731500,0.074443,0.262913,0.117690,0.178398,0.555843,0.443994,0.500923,119.034899
std,151313.257586,0.156899,0.176510,0.049939,0.223120,0.131845,0.118186,0.225480,0.148039,0.289952,26.468077
min,0.000000,0.076900,0.000000,0.023500,0.000005,0.000001,0.024300,0.025600,0.000000,0.000067,46.718000
25%,131040.750000,0.515850,0.610177,0.023500,0.069413,0.000001,0.077637,0.403921,0.357147,0.254933,101.070410
50%,262081.500000,0.634686,0.736337,0.066425,0.242502,0.074247,0.166327,0.564817,0.448437,0.511800,118.747660
75%,393122.250000,0.739179,0.864056,0.107343,0.396957,0.204065,0.268946,0.716633,0.543677,0.746000,136.686590
max,524163.000000,0.975000,1.000000,0.256401,0.995000,0.869258,0.599924,0.978000,1.000000,1.000000,206.037000

In [ ]:
training_df.isna().any()

id                           False
RhythmScore                  False
AudioLoudness                False
VocalContent                 False
AcousticQuality              False
InstrumentalScore            False
LivePerformanceLikelihood    False
MoodScore                    False
TrackDurationMs              False
Energy                       False
BeatsPerMinute               False
dtype: bool

In [ ]:
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
X_train= training_df.drop(["id", "BeatsPerMinute"], axis=1)
y_train= training_df["BeatsPerMinute"]

In [ ]:
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
testing_df= pd.read_csv("/content/drive/MyDrive/test.csv")
testing_df.head(10)

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy
0,524164,0.410013,-16.794967,0.023500,0.232910,0.012689,0.271585,0.664321,302901.5498,0.424867
1,524165,0.463071,-1.357000,0.141818,0.057725,0.257942,0.097624,0.829552,221995.6643,0.846000
2,524166,0.686569,-3.368928,0.167851,0.287823,0.210915,0.325909,0.304978,357724.0127,0.134067
3,524167,0.885793,-5.598049,0.118488,0.000005,0.376906,0.134435,0.487740,271790.3989,0.316467
4,524168,0.637391,-7.068160,0.126099,0.539073,0.068950,0.024300,0.591248,277728.5383,0.481067
5,524169,0.572976,-4.873283,0.041233,0.000005,0.043458,0.155836,0.662945,315545.1364,0.180800
6,524170,0.711520,-8.814040,0.074719,0.527942,0.445736,0.096897,0.747580,211423.0498,0.017867
7,524171,0.385830,-8.126094,0.023500,0.556661,0.087628,0.285547,0.644006,161117.6378,0.172467
8,524172,0.668328,-13.498035,0.057744,0.161520,0.094422,0.049369,0.379834,249847.6422,0.959133
9,524173,0.595037,-5.291299,0.023500,0.512736,0.000001,0.213435,0.372640,144727.4785,0.248867

In [ ]:
testing_df["TrackDurationMs"]= scaler.fit_transform(testing_df[["TrackDurationMs"]])
testing_df["AudioLoudness"]= scaler.fit_transform(testing_df[["AudioLoudness"]])

In [ ]:
testing_df.describe()

,id,RhythmScore,AudioLoudness,VocalContent,AcousticQuality,InstrumentalScore,LivePerformanceLikelihood,MoodScore,TrackDurationMs,Energy
count,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000,174722.000000
mean,611524.500000,0.632591,0.730868,0.074475,0.262903,0.117407,0.178317,0.555861,0.461390,0.500545
std,50438.041204,0.157229,0.177196,0.050024,0.222899,0.131628,0.118165,0.226218,0.153391,0.290550
min,524164.000000,0.140859,0.000000,0.023500,0.000005,0.000001,0.024300,0.025600,0.000000,0.000067
25%,567844.250000,0.514918,0.609246,0.023500,0.069448,0.000001,0.077821,0.403788,0.372539,0.253817
50%,611524.500000,0.634556,0.735634,0.066432,0.242412,0.073968,0.165956,0.566015,0.466141,0.511867
75%,655204.750000,0.739179,0.864035,0.107302,0.396870,0.202977,0.268133,0.716694,0.565158,0.746133
max,698885.000000,0.975000,1.000000,0.258857,0.995000,0.680914,0.599544,0.978000,1.000000,0.999867

In [ ]:
testing_df.isna().any()

id                           False
RhythmScore                  False
AudioLoudness                False
VocalContent                 False
AcousticQuality              False
InstrumentalScore            False
LivePerformanceLikelihood    False
MoodScore                    False
TrackDurationMs              False
Energy                       False
dtype: bool

In [ ]:
testing_df.describe()
X_test= testing_df.drop(["id"], axis=1)

In [ ]:
yp= model.predict(X_test)

In [ ]:
result=pd.DataFrame({"id": testing_df["id"], "BeatsPerMinute": yp})

In [ ]:
result

            id  BeatsPerMinute
0       524164      119.182670
1       524165      119.096745
2       524166      119.635912
3       524167      119.545436
4       524168      119.121189
...        ...             ...
174717  698881      119.373350
174718  698882      119.166232
174719  698883      118.738362
174720  698884      118.960553
174721  698885      119.433712

[174722 rows x 2 columns]

In [ ]:
from google.colab import files
result.to_csv("result.csv", index=False)
files.download("result.csv")